#=============================================== The Beginning of the Copyright Notice ===================================================
# The AUTHOR of this file and the owner of all exclusive rights in this file is Alexander Borisovich Prokopyev
# born on December 20, 1977 resident of the city of Kurgan, Russia;
# Series and Russian passport number of the AUTHOR (only the last two digits for each one): **22-****91
# Russian Individual Taxpayer Number of the AUTHOR (only the last four digits): ********2007
# Russian Insurance Number of Individual Ledger Account of the AUTHOR (only the last five digits): ***-***-859 04
# Copyright (C) Alexander B. Prokopyev, 2024, All Rights Reserved.
# Contact of the AUTHOR: a.prokopyev.resume at gmail dot com
#
# All source code and other content contained in this file is protected by copyright law.
# This file is licensed by the AUTHOR under AGPL v3 (GNU Affero General Public License): https://www.gnu.org/licenses/agpl-3.0.en.html
#
# THIS FILE IS LICENSED ONLY PROVIDED FOLLOWING RESTRICTIONS ALSO APPLY:
# Nobody except the AUTHOR may alter or remove this copyright notice from any copies of this file content (including modified fragments).
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
#
# ATTENTION: If potential user's or licensee's country laws collide or are not compatible with the terms of this copyright notice or 
# if a potential user or licensee does not agree with the terms of this copyright notice then such potential user or licensee  
# is STRONGLY PROHIBITED to use this file by any method.
#================================================== The End of the Copyright Notice ======================================================

---


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-14-deployment
  namespace: task-14
  labels:
    position: step-1
  annotations:
    kubernetes.io/change-cause: "bitnami/nginx:1.19.0"
spec:
  selector:
    matchLabels:
      app: task-14-app
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: task-14-app
    spec:
      containers:
      - name: nginx
        image: bitnami/nginx:1.19.0
        env:
          - name: NGINX_HTTP_PORT_NUMBER
            value: "8080"
        ports:
        - name: nginx
          containerPort: 8080
      - name: tool
        image: wbitt/network-multitool
        ports:
        - containerPort: 8081
        env:
          - name: HTTP_PORT
            value: "8081"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-14-deployment
  namespace: task-14
  labels:
    position: step-2
  annotations:
    kubernetes.io/change-cause: "bitnami/nginx:1.20.0"
spec:
  selector:
    matchLabels:
      app: task-14-app
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: task-14-app
    spec:
      containers:
      - name: nginx
        image: bitnami/nginx:1.20.0
        env:
          - name: NGINX_HTTP_PORT_NUMBER
            value: "8080"
        ports:
        - name: nginx
          containerPort: 8080
      - name: tool
        image: wbitt/network-multitool
        ports:
        - containerPort: 8081
        env:
          - name: HTTP_PORT
            value: "8081"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-14-deployment
  namespace: task-14
  labels:
    position: step-3
  annotations:
    kubernetes.io/change-cause: "bitnami/nginx:1.28.0"
spec:
  selector:
    matchLabels:
      app: task-14-app
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: task-14-app
    spec:
      containers:
      - name: nginx
        image: bitnami/nginx:1.28.0
        env:
          - name: NGINX_HTTP_PORT_NUMBER
            value: "8080"
        ports:
        - name: nginx
          containerPort: 8080
      - name: tool
        image: wbitt/network-multitool
        ports:
        - containerPort: 8081
        env:
          - name: HTTP_PORT
            value: "8081"
