---
driver:
  name: docker
platforms:  

  - name: Ubuntu
    image: ubuntu:latest
#   dockerfile: Dockerfile
    command: /lib/systemd/systemd
    privileged: true
#   pre_build_image: false

  - name: Centos8
    # you might want to add your own variables here based on what provisioning
    # you are doing like:
    image: quay.io/centos/centos:stream8
