---
version: "3.9"
services:
  k0s:
    container_name: k0s
    image: docker.io/k0sproject/k0s:v1.30.3-k0s.0
#    image: docker.io/k0sproject/k0s:v1.29.6-k0s.0
#    command: k0s controller --config=/etc/k0s/config.yaml --single --enable-worker
    command: k0s controller --config=/etc/k0s/config.yaml --enable-worker
    hostname: k0s
    privileged: true
    user: root # ?
    cgroup: host
    volumes:
      - /k0s:/var/lib/k0s
    ports:
      - "6443:6443"
    network_mode: "bridge"
    environment:
      K0S_CONFIG: |-
        apiVersion: k0s.k0sproject.io/v1beta1
        kind: ClusterConfig
        metadata:
          name: k0s
        # Any additional configuration goes here ...
