apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: user12
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dkWE5sY2pFeU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXJldEx0a203d1BheHZ5YXFnY2tYcTNZZ3RlU1pCcnJPNGtPS0svZEFyL2RYCktqbHY4SUpSZlE1MzFUZlZWK3NTTTRwanBaUjhkSjVubGZXMnBZYW94MlA5V0ZUR0R3RlMvdlUyMXBTRXdDTnQKdXJaUXkveCtNa2RWakZNVmZVVlJmS0prMU9INGpzTGN1Y3RIenFJRUR2QjJ1K3lhajdsdHZic1RsZmZNUWl6SApNUjQvVFJQcURoT3dKZHpBQW9NNzBhaTllK2ViQVl1Y25UajJBNThYTkNuNVNVRXl4b0ZOUTJQYjA3USttMFE1CmFGU3dwRFIvZVBNNkxTN2J2eTFqenFCaFUwbDV1WVZ3Mm9BVGVwVkdXQUR3REV2Y2psdWhIV2xSaEs5ZitmbEoKWEdwWFNBK1ZicU5lWmczTWs5dUl0NXhEYTZtVHNOb2ZScXRoL3d6QjVRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBSEdGMVdab0lOV0JXcXR1QjNQZUhwV0Rqb0V6bXFCQ0VPWHhuTTVySGZoc0dyU1h4Q1VjClJqdElzTXNLOVZjZU1FaVhUektVSFRzSk9ycTRScHFyenNmSnVxUTdRTzhOUzRlbUlYT2oyVXYvV2dnTWJlV3QKWGZ1MGFNYm5Td2pEVmp2Y1QyR1llL1J6aCtWcmo2MU51Q1R4bmdLVFBwRjBSaXBMdy9IOWE0VmRQM3pqUXhZagphenorTXAxT3E5cmU4dTJITDNHMnBmU1d5SnA2eUw3U0Q1YzFvTHMzeVFkcDBudjRoSm1aZDRjZTZHbFJxT3o0CmNNR3JTWFd0N3BTL0cxTDIrVmh4VDFha2Erb1pDN3hLV21Dd1FNS0xwb2llaytpbXFRQkFRalZ4ZlZ4VUVJS1IKZUFxQnFNdkFmRERCSVZsUUEvdW8vMDNTY1VHM3paSjN4bWM9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  groups:
    - system:authenticated
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 7776000
  usages:
    - digital signature
    - key encipherment
    - client auth
