{
 "title": "Netology 10-monitoring-03-grafana",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[1m])) )* 100",
     "legendFormat": "Utilization, %"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free Memory, Bytes" }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(node_load1{job=\"node-exporter\"})",
     "legendFormat": "LA1"
    },
    {
     "expr": "avg(node_load5{job=\"node-exporter\"})",
     "legendFormat": "LA5"
    },
    {
     "expr": "avg(node_load15{job=\"node-exporter\"})",
     "legendFormat": "LA15"
    }
   ]
  },
  {
   "title": "Free disk space on FS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "node_filesystem_avail_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}