---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lesson
  namespace: task-4-all
spec:
  selector:
    matchLabels:
      app: lesson
  replicas: 3
  template:
    metadata:
      labels:
        app: lesson
    spec:
      containers:
      - name: nginx
        image:  bitnami/nginx
        ports:
        - name: nginx
          containerPort: 80
      - name: tool1
        image: wbitt/network-multitool
        ports:
        - name: tool
          containerPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
   name: tool2
   namespace: task-4-all
#   labels:
#     app: tool2

spec:
   containers:
     - name: tool2
       image: wbitt/network-multitool
       ports:
        - name: tool
          containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: int
  namespace: task-4-all
spec:
  selector:
    app: lesson
  ports:
    - name: nginx
      port: 9001
      targetPort: nginx
    - name: tool
      port: 9002
      targetPort: tool

---
apiVersion: v1
kind: Service
metadata:
  name: ext
  namespace: task-4-all
spec:
  type: NodePort
  selector:
    app: lesson
  ports:
    - name: nginx
      port: 80
      targetPort: nginx
      nodePort: 30001
    - name: tool
      port: 8080
      targetPort: tool
      nodePort: 30002

      