
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: task-9
spec:
  selector:
    matchLabels:
      app: task-9-app
  replicas: 1
  template:
    metadata:
      labels:
        app: task-9-app
    spec:
      containers:
        - name: nginx
          image: bitnami/nginx:1.19.0

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: netology-viewer
  namespace: task-9
subjects:
- kind: User
  name: netology-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: viewer
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: task-9
  name: viewer
rules:
- apiGroups: [""]
  resources: ["pods","pods/log"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  