---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lesson
  namespace: {{ inventory.parameters.target_name }}
spec:
  selector:
    matchLabels:
      app: lesson
  replicas: 3
  template:
    metadata:
      labels:
        app: lesson
    spec:
      containers:
      - name: nginx
        image:  {{ inventory.parameters.NginxImage }}
        ports:
        - name: nginx
          containerPort: 80
      - name: tool1
        image: {{ inventory.parameters.ToolImage }}
        ports:
        - name: tool
          containerPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
   name: tool2
   namespace: {{ inventory.parameters.target_name }}
#   labels:
#     app: tool2

spec:
   containers:
     - name: tool2
       image: {{ inventory.parameters.ToolImage }}
       ports:
        - name: tool
          containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: int
  namespace: {{ inventory.parameters.target_name }}
spec:
  selector:
    app: lesson
  ports:
    - name: nginx
      port: {{ inventory.parameters.NginxIntPort }}
      targetPort: nginx
    - name: tool
      port: {{ inventory.parameters.ToolIntPort }}
      targetPort: tool

---
apiVersion: v1
kind: Service
metadata:
  name: ext
  namespace: {{ inventory.parameters.target_name }}
spec:
  type: NodePort
  selector:
    app: lesson
  ports:
    - name: nginx
      port: 80
      targetPort: nginx
      nodePort: {{ inventory.parameters.NginxExtPort }}
    - name: tool
      port: 8080
      targetPort: tool
      nodePort: {{ inventory.parameters.ToolExtPort }}

      